### ISSUE TITLE
Evaluate the difference of "old" Stanford CoreNLP and SCNLP 4.2.2

### ISSUE THREAD

**Issue by dfuchss** [ArDoCo/Core#23]
After changing the stanford version to 4.2.2 (PR #22), the values (P,R,F1) changed a bit.
Investigations will follow ..
![image](https://user-images.githubusercontent.com/22198798/125447941-48fdf28f-fb15-4925-b100-62b25eda35d1.png)

**Comment by Gram21** [comment]
The problem for the performance degradation was because the (short) name for the dependency type for direct objects apparently changed from previously DOBJ to OBJ. This caused an issue when trying to check for that exact dependency type. Will be fixed in 87f942f
